version: '3.7'

networks:
  default:
    name: zimbra
    external: true

services:
  zimbra:
    container_name: zimbra
    hostname: mail.yurdusev.com
    build:
      context: ./docker
    ports:
      - '25:25'
      - '8088:80'
      - '465:465'
      - '587:587'
      - '110:110'
      - '143:143'
      - '993:993'
      - '995:995'
      - '4443:443'
      - '8080:8080'
      - '8443:8443'
      - '7071:7071'
      - '9071:9071'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    environment:
      - PASSWORD=123456aA
    volumes:
      - ./data:/opt/zimbra

